### PR TITLE
Go //go:build lines added

### LINKED ISSUE #115: Golang directive for test files
related to https://github.com/ldsec/medco/issues/114

Since go1.17, the directive // +build is ignored and //go:build should be used instead.

See https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#Abstract and https://golang.org/doc/go1.17 under Tools > //go:build lines

Go fmt added the correct directive syntax to all _test.go file. This was tested on a environment that use Go 1.14 as well, and the fix is seemless.

(Runner with current config use the most recent version above or equal to 1.14, namely 1.17 at this time)

### PR DESCRIPTION
**Pull request by nfreundl**
//go:build lines added as runner uses Go 1.17, requiring this line in addition to //+build syntax

### CODE REVIEW

**Comment by f-marino** [comment]
Do we want to keep both notations? Maybe it's easier to just update everything to 1.17?

**Comment by nfreundl** [comment]
> Do we want to keep both notations? Maybe it's easier to just update everything to 1.17?

If we do so, we have to change
 - connector/util/server/oidc_provider.go and
 - connector/util/server/oidc_provider.go
as jwt library have updated.

These are a few lines of code, but as it concerns security topics, I don't want to change those on my side alone beause I won't fully understand the implication of the modifications I'll bring.

see change log of jwt library https://github.com/lestrrat-go/jwx/blob/main/Changes


Do you want to keep the extra // +build lines or do you prefer that we change security files  together ?

**Comment by f-marino** [comment]
@nfreundl I updated the files related to security, can you take care of getting rid of the old build directives and check that everything works as expected?

**Comment by nfreundl** [comment]
Now I have errors with unlynx protocols in CI tests. Unfortunately, these errors do not occur on my local environment.

```
=== RUN   TestConvertOntology
I : loaderI2B2_test.go:25 (i2b2_test.getRoster) - Creating local test roster
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:14:30 on address local://127.0.0.1:2000
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2001
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:14:30 on address local://127.0.0.1:2010
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2011
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:14:30 on address local://127.0.0.1:2020
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2021
2 : loaderI2B2.go:866 (i2b2.EncryptAndTag)   - Finished encrypting the sensitive data... [11] ( 122.061583ms )
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: tagging_loading_phase
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
F : loaderI2B2.go:880 (i2b2.EncryptAndTag)   - Error during DDT: sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference
FAIL	github.com/ldsec/medco/loader/i2b2	51.090s


=== RUN   TestServiceDDT
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:04 on address local://127.0.0.1:2000
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2001
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:05 on address local://127.0.0.1:2010
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2011
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:05 on address local://127.0.0.1:2020
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2021
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: 
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: testDDTSurvey_
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: testDDTSurvey_
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: testDDTSurvey_0
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 2 is creating a DDT survey with ID: testDDTSurvey_2
2 : api.go:41 (services.(*API).SendSurveyDDTRequestTerms) - Client 0 is creating a DDT survey with ID: testDDTSurvey_0
2 : websocket.go:274 (v3.wsHandler.ServeHTTP) - ws request from 127.0.0.1:53842: medco/SurveyDDTRequest
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
    service_test.go:92: Client 0  service did not start:  sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
    service_test.go:92: Client 0  service did not start:  sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference
==================
WARNING: DATA RACE
Write at 0x00c000001709 by goroutine 27:
  testing.(*common).FailNow()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:731 +0x4f
  testing.(*common).Fatal()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:800 +0x89
  github.com/ldsec/medco/unlynx/services_test.TestServiceDDT.func1()
      /home/runner/work/medco/medco/unlynx/services/service_test.go:92 +0x45b

Previous write at 0x00c000001709 by goroutine 28:
  testing.(*common).FailNow()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:731 +0x4f
  testing.(*common).Fatal()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:800 +0x89
  github.com/ldsec/medco/unlynx/services_test.TestServiceDDT.func1()
      /home/runner/work/medco/medco/unlynx/services/service_test.go:92 +0x45b

Goroutine 27 (running) created at:
  github.com/ldsec/medco/unlynx/services_test.TestServiceDDT()
      /home/runner/work/medco/medco/unlynx/services/service_test.go:82 +0x58d
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1123 +0x202

Goroutine 28 (finished) created at:
  github.com/ldsec/medco/unlynx/services_test.TestServiceDDT()
      /home/runner/work/medco/medco/unlynx/services/service_test.go:82 +0x58d
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1123 +0x202
==================
2 : service.go:91 (services.(*Service).HandleSurveyDDTRequestTerms) - local://127.0.0.1:2020  received a SurveyDDTRequestTerms: testDDTSurvey_2
1 : deterministic_tagging_protocol.go:138 (protocols.(*DeterministicTaggingProtocol).Start) - [local://127.0.0.1:2020]  starts a Deterministic Tagging Protocol on  100  element(s)
1 : deterministic_tagging_protocol.go:200 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2000  preparation round for deterministic tagging
1 : deterministic_tagging_protocol.go:200 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2010  preparation round for deterministic tagging
1 : deterministic_tagging_protocol.go:200 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2020  preparation round for deterministic tagging
1 : deterministic_tagging_protocol.go:264 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2000  carried on deterministic Tagging. 100
1 : deterministic_tagging_protocol.go:264 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2010  carried on deterministic Tagging. 100
1 : deterministic_tagging_protocol.go:262 (protocols.(*DeterministicTaggingProtocol).Dispatch) - local://127.0.0.1:2020  completed deterministic Tagging ( 100 row )
1 : service_test.go:94 (services_test.TestServiceDDT.func1) - Time: map[DDTRequestTime:3.460471952s TaggingTimeCommunication:2.376332751s TaggingTimeExec:1.003428762s]
    service_test.go:100: 
        	Error Trace:	service_test.go:100
        	Error:      	Not equal: 
        	            	expected: 100
        	            	actual  : 0
        	Test:       	TestServiceDDT
2 : websocket.go:239 (v3.wsHandler.ServeHTTP.func1) - ws close 127.0.0.1:53842 n 1 rx 8996 tx 6659
    testing.go:1038: race detected during execution of test
--- FAIL: TestServiceDDT (4.91s)

=== RUN   TestServiceKS
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:09 on address local://127.0.0.1:2000
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2001
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:10 on address local://127.0.0.1:2010
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2011
1 : server.go:217 (v3.(*Server).Start)       - Starting server at 2021-09-17 14:15:10 on address local://127.0.0.1:2020
2 : websocket.go:175 (v3.(*WebSocket).start) - Starting to listen on 0.0.0.0:2021
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 0 is creating a KS survey with ID: 
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 0 is creating a KS survey with ID: testKSRequest
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 0 is creating a KS survey with ID: testKSRequest
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 0 is creating a KS survey with ID: testKSRequest
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 0 is creating a KS survey with ID: testKSRequest_0
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 1 is creating a KS survey with ID: testKSRequest_1
2 : api.go:65 (services.(*API).SendSurveyKSRequest) - Client 2 is creating a KS survey with ID: testKSRequest_2
2 : websocket.go:274 (v3.wsHandler.ServeHTTP) - ws request from 127.0.0.1:52448: medco/SurveyKSRequest
2 : service.go:142 (services.(*Service).HandleSurveyKSRequest) - local://127.0.0.1:2010  received a SurveyKSRequest: testKSRequest_1
2 : key_switching_protocol.go:156 (protocols.(*KeySwitchingProtocol).Start) - [KEY SWITCHING PROTOCOL] <Drynx> Server local://127.0.0.1:2010  started a Key Switching Protocol
E : websocket_client.go:547 (v3.(*Client).closeConn) - Error while sending closing type: websocket: close sent
    service_test.go:153: Client 0  service did not start:  sending: connection read: websocket: close 1002 (protocol error): unexpected error: panic: runtime error: invalid memory address or nil pointer dereference
2 : websocket.go:274 (v3.wsHandler.ServeHTTP) - ws request from 127.0.0.1:53874: medco/SurveyKSRequest
2 : service.go:142 (services.(*Service).HandleSurveyKSRequest) - local://127.0.0.1:2020  received a SurveyKSRequest: testKSRequest_2
2 : key_switching_protocol.go:156 (protocols.(*KeySwitchingProtocol).Start) - [KEY SWITCHING PROTOCOL] <Drynx> Server local://127.0.0.1:2020  started a Key Switching Protocol
2 : websocket.go:239 (v3.wsHandler.ServeHTTP.func1) - ws close 127.0.0.1:53874 n 1 rx 694 tx 304
2 : websocket.go:239 (v3.wsHandler.ServeHTTP.func1) - ws close 127.0.0.1:52448 n 1 rx 694 tx 304
1 : service_test.go:163 (services_test.TestServiceKS.func1) - Time: map[KSRequestTime:133.105299ms KSTimeCommunication:111.52994ms KSTimeExec:0s]
1 : service_test.go:163 (services_test.TestServiceKS.func1) - Time: map[KSRequestTime:131.333379ms KSTimeCommunication:123.147426ms KSTimeExec:0s]
--- FAIL: TestServiceKS (0.53s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 63 [running]:
testing.tRunner.func1.1(0xdb1200, 0xc0002dea60)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1072 +0x46a
testing.tRunner.func1(0xc000086900)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1075 +0x636
panic(0xdb1200, 0xc0002dea60)
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:975 +0x47a
go.dedis.ch/onet/v3.(*LocalTest).CloseAll(0xc00009a270)
	/home/runner/go/pkg/mod/go.dedis.ch/onet/v3@v3.2.10/local.go:281 +0xd37
panic(0xdb1200, 0xc0002dea60)
	/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:975 +0x47a
github.com/ldsec/medco/unlynx/services_test.TestServiceKS(0xc000086900)
	/home/runner/work/medco/medco/unlynx/services/service_test.go:171 +0x1094
testing.tRunner(0xc000086900, 0xe2b4c0)
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.15/x64/src/testing/testing.go:1168 +0x5bc
FAIL	github.com/ldsec/medco/unlynx/services	5.564s
```

**Pull request closed without merging**
