### PR TITLE
Modifier paths

### PR DESCRIPTION
**Pull request by nfreundl**
WUI organizes concepts in a tree structure. Concepts arrive in a flat list from a search request and the WUI reconstructs the tree using the paths.

Specifically, the child-to-parent relationship is characterized by a path matching:  for instance, /E2ETEST/e2etest/1/ is a child of  /E2ETEST/e2etest/.

When  a level-1 modifier or modifier folder is among the returned elements of the search request, its path does not match (path /E2ETEST/modifiers/ is not a child of /E2ETEST/e2etest/).

Solution, WUI should also test for path matching with the applied path field and this could be return by search request. For non-modifier element, applied path is defaulted to "@" as it is already the case in ontology.

### CODE REVIEW

**Review by f-marino — APPROVED** [review]

**Review by f-marino — COMMENTED** [review]
Why does the WUI uses this path matching approach? This is not what the i2b2 interface does, it just uses the backend ontology service (which medco can query through the i2b2 wrapper) to build the ontology tree. Why do not we use the same approach?

**Comment by nfreundl** [comment]
In older versions without I2B2 (correct me if I am wrong), search results could come from anywhere in tree and this made the embedded for-loop (which reconstructs parent-child relationships using paths) necessary  in WUI tree.

If i2b2 API only returns direct children and 1st-level modifiers, this re-build process of tree won't be necessary, as well this PR.

**Comment by f-marino** [comment]
this is indeed what the i2b2 APIs do. However I am not aware of how it worked in old medco versions and I do not know if we want to support scenarios that do not involve i2b2. @mickmis ?

**Comment by mickmis** [comment]
This behavior is indeed what used to be the case before, when we were still using PICSURE. Notably because some systems could return the whole tree of concepts at once. 

Some time ago we had a discussion with @nfreundl and I had expressed that it would be better to keep this more generic behavior. For a long time and up until recently MedCo has been sold as a system that does not depend on i2b2, and that it could be swapped with another system.

The more we do this kind of i2b2-specific changes, the less this is true. But truth is i2b2 is already very deeply intertwined with MedCo at that point, so I am not sure this is still worth pursuing...

@nfreundl, in the PR #52 of @f-marino that was just merged, the applied path is sent back from the API. Is this enough for you and does that make this PR redundant?

**Comment by f-marino** [comment]
@nfreundl besides that, have you checked that the content of the m_applied_path field would help to implement this pattern matching approach for modifiers? Most of the time it does not contain the full concept path, but it stops at one of its ancestors followed by a %. Moreover, I do not know if you are aware of the existence of the [M_EXCLUSION_CD column](https://community.i2b2.org/wiki/display/ServerSideDesign/M_EXCLUSION_CD) in the ontology table, which can make even trickier to rely on m_applied_path to derive the ontology tree structure.

**Comment by nfreundl** [comment]
The difference #53 introduces is that the applied paths are returned from search concept children.

About exclusion paths, are modifiers also returned from search concept children if the parent's path match the excluded paths ?

**Comment by f-marino** [comment]
@mickmis actually the current implementation does not return the applied path, this is actually what @nfreundl implemented in this PR.
@nfreundl if M_EXCLUSION_CD is set, the the path in m_applied_path is an exclusion path, meaning that that modifier does not apply to the concept(s) comprised in m_applied_path. This is useful when there is another modifier with the same modifier_path and a m_applied_path which is a superset of the first one.

example
modifiers/1/ has m_applied_path /e2etest/%
modifiers/1/ has m_applied_path /e2etest/3/ and m_exclusion_cd set

this means that modifiers/1/ applies to all descendants of /e2etest/ except /e2etest/3/

**Comment by f-marino** [comment]
@mickmis in my opinion is farfecthed to say that medco is i2b2 independent. If we want to support other systems we should implement wrappers for them. I would avoid to maintain "general" solutions which are not as reliable as the ones offered by the framework we are using and that will require adjustments anyway if and when we will consider other frameworks.

**Comment by mickmis** [comment]
For the record, after our discussion today with @nfreundl and @f-marino :

- the implementation of tree parsing in glowing-bear will be modified to match i2b2 structure
- this PR is dismissed because not needed anymore

**Comment by nfreundl** [comment]
Applied path is actually needed, but for other reasons. When calling the API request searchModifier, there are three needed filed: parent modifier path, applied path and applied concept.

Applied path must be exact for this request: /folder/concept/ does not match /folder/%; however, user has no information about how the applied path was written by the loaders, except if one coerces the way it is done, or if search concept request returns the applied path.
The second solution looks the easiest and the most flexible.

**Review by f-marino — APPROVED** [review]

**Pull request merged**
