### PR TITLE
Review authorizations, query/response for auto-selection

### PR DESCRIPTION
**Pull request by JoaoAndreSa**
I changed the `MedCoNodeExploreQueryHandler` to read the highest permission from the user token `user.Authorizations.ExploreQuery` and create the query according to this type. 

In the meantime I will add a test for naive obfuscation in the connector. @mickmis did I miss anything?

### CODE REVIEW

**Review by mickmis — APPROVED** [review]
Thanks changes are good, just ensure the CI passes and it's all good.
(FYI I updated the base branch for the diff to be accurate)

**Comment by mickmis** [comment]
Actually additional stuff that I noticed now to be updated for consistency:
- from medco-connector.yml remove:
```yml
      type:
        $ref: "#/definitions/exploreQueryType"
```
To remove the option from the API to select the query type (don't forget to run again `make swagger-gen`)

- from medco-cli-client/main.go: 
Remove from the CLI client the option of setting the query type (both from the argument and from the "usage" displayed to the user). It means also updating the e2e tests in `test/` to not use this flag.

**Comment by JoaoAndreSa** [comment]
> Actually additional stuff that I noticed now to be updated for consistency:
> 
> * from medco-connector.yml remove:
> 
> ```yaml
>       type:
>         $ref: "#/definitions/exploreQueryType"
> ```
> 
> To remove the option from the API to select the query type (don't forget to run again `make swagger-gen`)
> 
> * from medco-cli-client/main.go:
>   Remove from the CLI client the option of setting the query type (both from the argument and from the "usage" displayed to the user). It means also updating the e2e tests in `test/` to not use this flag.

Fixed in d587ac4. I just need to revamp the end-to-end tests now.

**Comment by JoaoAndreSa** [comment]
@mickmis this is ready to merge :)

One side note. I added an obfuscation test that cannot necessarily fail (it gives a warning if no noise is added to the results). I did not find any other better way to test this feature.

**Pull request merged**
